version: '3'

services:
    mysql:
        image: mysql:5.7
        environment: 
            MYSQL_ROOT_PASSWORD: myroot
            MYSQL_DATABASE: confiax
        ports:
            - 3306:3306
        volumes:
            - db-config:/etc/mysql
            - mysql_data:/var/lib/mysql
    backend:
        build:
            context: .
            dockerfile: ./confiax-backend/Dockerfile
        command: yarn start:dev
        image: api
        depends_on: 
           - mysql
        stdin_open: true
        tty: true
        volumes: 
            - ./confiax-backend:/usr/src/app
        ports:
            - 3333:3333
    frontend:
        build:
            context: .
            dockerfile: ./confiax-frontend/Dockerfile
        command: yarn start
        image: web
        stdin_open: true
        tty: true
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
        ports:
            - 3000:3000
        volumes: 
            - ./confiax-frontend:/usr/src/app
volumes: 
    db-config:
    mysql_data:

